services:

    casino.softwareshinobi.online:

        container_name: casino.softwareshinobi.online

        image: softwareshinobi/casino.softwareshinobi.online:bonus

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80
