services:

    casino.softwareshinobi.com:

        container_name: casino.softwareshinobi.com

        image: softwareshinobi/casino.softwareshinobi.com

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80

    casino.softwareshinobi.com1:

        container_name: casino.softwareshinobi.com1

        image: softwareshinobi/casino.softwareshinobi.com

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 80:80
