services:

    casino.softwareshinobi.com:

        container_name: casino.softwareshinobi.com

        image: softwareshinobi/casino.softwareshinobi.com:bonus

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80
